import {Dimensions, StatusBar} from 'react-native';

export default {
  FONT_SIZE_SM: 12,
  FONT_SIZE_M: 14,
  FONT_SIZE_L: 16,
  FONT_SIZE_XL: 24,
  FONT_SIZE_XXL: 56,
  SIZE_XS: 8,
  SIZE_SM: 12,
  SIZE_M: 14,
  SIZE_L: 16,
  SIZE_XL: 24,
  SIZE_XXL: 54,
  INPUT_HEIGHT: 50,
  INPUT_WIDTH: '100%',
  INPUT_BORDER_SIZE: 1,
  INPUT_BORDER_RADIUS: 8,
  INPUT_VERTICAL_SPACING: 16,
  INPUT_HORIZONTAL_SPACING: 18,
  BUTTON_HEIGHT: 50,
  BUTTON_WIDTH: '100%',
  CARD_BORDER_RADIUS: 8,
  BUTTON_BORDER_SIZE: 1,
  BUTTON_BORDER_RADIUS: 8,
  BUTTON_HORIZONTAL_SPACING: 16,
  HEADER_BG_HEIGHT: Dimensions.get('window').height * 0.28,
  HEADER_BAR_HEIGHT: 56,
  HEADER_LOGO_HEIGHT: 75,
  HEADER_LOGO_WIDTH: 75,
  HEADER_ICON_HEIGHT: 56,
  HEADER_ICON_WIDTH: 56,
  MODAL_BORDER_RADIUS: 16,
  ICON_SIZE: 24,
  SPACING: 32,
  WINDOW_HEIGHT: Dimensions.get('window').height,
  WINDOW_WIDTH: Dimensions.get('window').width,
  SCREEN_WIDTH: Dimensions.get('screen').width,
  SCREEN_HEIGHT: Dimensions.get('screen').height,
  STATUS_BAR_HEIGHT: StatusBar.currentHeight,
  ASPECT_RATIO:
    Dimensions.get('window').width / Dimensions.get('window').height,
  LATITUDE: -1.9297692,
  LONGITUDE: 30.0572045,
  LATITUDE_DELTA: 0.0122,
  LONGITUDE_DELTA:
    0.0122 * (Dimensions.get('window').width / Dimensions.get('window').height),
};
